#!/usr/bin/env python3
"""
Generate db/seed/seed.sql — Riverbend demo data.

Deterministic (fixed RNG seed) so the committed seed.sql is reproducible. It
PRESERVES the hand-authored teaching fixtures verbatim:
  * Maria Gonzalez as THREE patient rows (1042, 1330, 1588) with the penicillin
    allergy recorded only under 1330 (duplicate-patient / no-MPI debt).
  * James O'Brien (1043) and Aisha Khan (1601).
  * Two confirmed appointments for the SAME slot 88231 ~400ms apart (retry race).
  * The PHI-laden audit_logs rows (audit-is-logging debt).
  * Week 4 catch-up: deliberately different patient_access_grants per user
    (frontdesk/drpatel/drnguyen) — see that INSERT's own comment below for
    exactly who is granted what and why frontdesk is NOT granted 1043.
and then layers a few hundred realistic rows on top so the database reads like a
real, lived-in clinic network.

Run:  python3 db/seed/generate_seed.py  > db/seed/seed.sql
"""
import base64
import hashlib
import random
from datetime import datetime, timedelta

random.seed(2026)

# --- password hashing (django-style pbkdf2_sha256; mirrored in gateway/security) -
def hash_password(password: str, salt: str, iterations: int = 260000) -> str:
    dk = hashlib.pbkdf2_hmac("sha256", password.encode(), salt.encode(), iterations)
    return f"pbkdf2_sha256${iterations}${salt}${base64.b64encode(dk).decode()}"

DEMO_PASSWORD = "portal123"   # all seeded accounts; documented in README/runbook

def sql_str(v):
    if v is None:
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"

OUT = []
def emit(line=""):
    OUT.append(line)

emit("-- Riverbend demo seed data. GENERATED by db/seed/generate_seed.py — do not")
emit("-- hand-edit; change the generator and re-run. Deterministic (seed=2026).")
emit("--")
emit("-- Teaching fixtures preserved verbatim: Maria Gonzalez triple (1042/1330/")
emit("-- 1588) with the penicillin allergy only under 1330; the double-booked slot")
emit("-- 88231; and the PHI-laden audit_logs rows.")
emit()

# ---------------------------------------------------------------------------
# users — the seeded staff still carry the deprecated flat 'staff' role, which
# is the point: migrating real accounts onto the nine-role grid is a separate,
# roster-gated piece of work, and this seed is what "before the migration"
# looks like.
#
# Two exceptions, added deliberately: `drkim` and `drnguyen` (2026-08-22,
# promoted from legacy `staff`) carry role='clinician'. The S3 review queue is
# gated on summary_review.decide, which `staff` does NOT hold — correctly,
# because deciding releases withheld clinical content to a patient and no
# legacy account should be able to do that. TWO clinical accounts, not one, so
# the shared-queue case (a patient granted to more than one reviewer — see
# patient 1738 below) is demonstrable at all; a single clinician account can
# only ever prove exclusive access, never overlap. This is not the account
# migration; it is two demo accounts with the roles they would obviously be
# assigned. Every other account here keeps the flat legacy role on purpose —
# tests/integration/test_review_queue_flow.py's negative test
# (test_a_legacy_staff_account_cannot_reach_the_queue) needs real accounts that
# are STILL `staff` to prove the containment against, and drpatel is that
# account for the treating-provider-but-not-a-reviewer case specifically.
# ---------------------------------------------------------------------------
_DEFAULT_ROLE = "staff"

USERS = [
    ("mokonkwo",  "Maya Okonkwo (COO)"),
    ("frontdesk", "Front Desk (Riverbend Main)"),
    ("rdelgado",  "Rosa Delgado (Registration)"),
    ("jpark",     "Jin Park (Registration)"),
    ("drpatel",   "Dr. Anil Patel"),
    ("drnguyen",  "Dr. Anita Nguyen", "clinician"),
    ("drlee",     "Dr. Sandra Lee"),
    ("billing1",  "Tom Reyes (Billing)"),
    ("roiclerk",  "Dana White (ROI Clerk)"),
    ("labtech",   "Lab Intake"),
    ("nurse_kc",  "Karen Cole, RN"),
    ("itadmin",   "Helix Support"),
    # Reviewer for the S3 queue — see the note above on why these are not 'staff'.
    ("drkim",     "Dr. Grace Kim", "clinician"),
]

# Pre-activated patient portal accounts (2026-08-22). Only 1738 and 1739 —
# NOT 1042 or 1737, which stay invite-ready with no account. 1042 specifically
# must stay account-less: tests/integration/test_patient_invitation_lifecycle.py
# issues a fresh invitation against the LIVE seeded database for patient 1042,
# and an already-active account there would trip issuance's own
# already-has-an-account guard (services/gateway/app.py::issue_patient_invitation)
# before the test's own scenario ever runs. 1737 stays invite-ready by the
# fixture's own design — it is the patient the "front desk issues an
# invitation" demo beat is built around.
#
# username_for_patient's format (patient-{id}) is duplicated here rather than
# imported — this generator has no import path to services/gateway/
# patient_invitations.py (adr/0001, no shared package) — so if that format
# ever changes, this literal needs updating too.
PATIENT_USERS = [
    (1738, "Thomas Johnson"),
    (1739, "Aisha Taylor"),
]
PATIENT_DEMO_PASSWORD = "portalportal123"  # documented in docs/runbook.md; meets the 12-char activation floor

emit("INSERT INTO users (id, username, password_hash, full_name, role, created_at) VALUES")
rows = []
for i, entry in enumerate(USERS, start=1):
    uname, full = entry[0], entry[1]
    role = entry[2] if len(entry) > 2 else _DEFAULT_ROLE
    salt = f"riverbend{i:02d}saltval0"  # fixed -> deterministic output
    h = hash_password(DEMO_PASSWORD, salt)
    rows.append(
        f" ({i}, {sql_str(uname)}, {sql_str(h)}, {sql_str(full)}, {sql_str(role)}, now())"
    )
emit(",\n".join(rows) + ";")
# The two patient-role accounts are inserted separately, AFTER the patients
# table exists (below) — users.patient_id carries a real FOREIGN KEY to
# patients(id) with no DEFERRABLE clause (db/schema.sql), so inserting a
# patient_id here, before any patients row exists, would fail the load
# outright rather than merely being out of order.
next_user_id = len(USERS) + 1
patient_user_id_of = {}
for patient_id, full_name in PATIENT_USERS:
    patient_user_id_of[patient_id] = next_user_id
    next_user_id += 1
emit(f"SELECT setval('users_id_seq', {next_user_id - 1}, true);")
emit()

# ---------------------------------------------------------------------------
# patients — fixtures first, then ~250 generated
# ---------------------------------------------------------------------------
emit("INSERT INTO patients (id, mrn, name, dob, ssn, gender, address, phone, email, notes, created_via, created_at) VALUES")
# Curated demo fixtures (2026-08-22): patients 1042/1737/1738/1739 are pinned
# ids with fully hand-authored, deterministic charts backing the four demo
# workflows (records, patient results, scheduling, review, agent-summary).
# CURATED_IDS below excludes them from every RANDOM per-patient generation
# loop that follows (encounters, records, insurance, appointments) so nothing
# random ever gets layered onto a chart the demo depends on reading exactly
# the same way every rehearsal. 1330/1588 are a DIFFERENT thing — Maria
# Gonzalez duplicate-chart candidates — and are deliberately NOT curated: they
# keep whatever random encounters/records they already got, because staying
# incomplete is the point of them (RIV-160), not a gap to close.
CURATED_IDS = frozenset({1042, 1737, 1738, 1739})
fixture_patients = [
    (1042, "M4471", "Maria Gonzalez", "1971-03-02", "412-55-9981", "F", "118 Maple Ave, Beverly Hills, CA 90210", "310-555-0147", "maria.g@example.com", "Prefers morning appts.", "self_service", "2026-06-22 09:14:06"),
    (1043, "M5012", "James O'Brien",  "1958-11-19", "501-22-7734", "M", "42 Birch St, Riverbend, CA 90211", "310-555-0199", "jobrien@example.com", "Hard of hearing.", "self_service", "2026-06-22 09:17:27"),
    (1330, "M4471", "Maria Gonzales", "1971-03-02", "412-55-9981", "F", "118 Maple Ave, Beverly Hills, CA 90210", "310-555-0147", "maria.g@example.com", "PCN allergy noted at front desk.", "self_service", "2026-06-22 09:21:45"),
    (1588, "M4471", "M. Gonzalez",    "1971-02-03", "412-55-9981", "F", "118 Maple Ave, Beverly Hills, CA 90210", "310-555-0147", None, "", "self_service", "2026-06-22 09:55:06"),
    (1601, "M6620", "Aisha Khan",     "1989-07-14", "623-41-2210", "F", "900 Cedar Rd, Riverbend, CA 90211", "310-555-0210", "akhan@example.com", "", "front_desk", "2026-06-23 10:02:00"),
    # Diabetes: the A1c 7.5%->6.2% trend below is this patient's own chart, not
    # a coincidence with the synthetic agent corpus's illustrative numbers.
    (1737, "M7370", "Priya Khan",     "1985-09-10", "701-22-3348", "F", "27 Sunset Blvd, Riverbend, CA 90211", "310-555-0731", "pkhan@example.com", "Type 2 diabetes, dietary counseling ongoing.", "self_service", "2026-03-05 08:40:00"),
    # Hypertension: systolic BP 158->132 mmHg.
    (1738, "M7381", "Thomas Johnson", "1962-04-22", "702-18-5591", "M", "615 Grand Ave, Pasadena, CA 91101", "310-555-0738", "tjohnson@example.com", "Hypertension, on lisinopril.", "front_desk", "2026-03-18 09:10:00"),
    # Asthma: peak flow (quotable, non-arithmetic) + O2 saturation 90%->96%.
    (1739, "M7392", "Aisha Taylor",   "1996-12-01", "703-44-2287", "F", "48 Pine St, Glendale, CA 91201", "310-555-0739", "ataylor@example.com", "Asthma, rescue inhaler prescribed.", "self_service", "2026-03-22 14:05:00"),
]
FIRST = ["James","Mary","Robert","Patricia","John","Jennifer","Michael","Linda","David","Elizabeth",
         "William","Barbara","Richard","Susan","Joseph","Jessica","Thomas","Karen","Aisha","Wei",
         "Carlos","Fatima","Hiroshi","Olga","Samuel","Grace","Derek","Nadia","Luis","Priya",
         "Marcus","Helen","Andre","Sofia","Victor","Renee","Omar","Beatriz","Ethan","Maya"]
LAST = ["Smith","Johnson","Williams","Brown","Jones","Garcia","Miller","Davis","Rodriguez","Martinez",
        "Hernandez","Lopez","Gonzalez","Wilson","Anderson","Thomas","Taylor","Moore","Jackson","Martin",
        "Lee","Perez","Thompson","White","Harris","Sanchez","Clark","Ramirez","Lewis","Robinson",
        "Walker","Young","Allen","King","Wright","Scott","Torres","Nguyen","Hill","Flores","Khan","Okafor"]
STREETS = ["Maple Ave","Birch St","Cedar Rd","Oak Ln","Pine St","Elm Dr","Sunset Blvd","River Rd",
           "Lake Ave","Hill St","2nd St","Park Pl","Mission Rd","Valley Way","Grand Ave"]
CITIES = [("Riverbend","90211"),("Beverly Hills","90210"),("Glendale","91201"),
          ("Pasadena","91101"),("Burbank","91502"),("Inglewood","90301")]
GENDERS = ["F","M","M","F","X"]

prows = []
for p in fixture_patients:
    pid, mrn, name, dob, ssn, g, addr, phone, email, notes, via, created = p
    prows.append(f" ({pid}, {sql_str(mrn)}, {sql_str(name)}, {sql_str(dob)}, {sql_str(ssn)}, {sql_str(g)}, {sql_str(addr)}, {sql_str(phone)}, {sql_str(email)}, {sql_str(notes)}, {sql_str(via)}, {sql_str(created)})")

gen_patient_ids = []
pid = 1602
generated_count = 0
while generated_count < 250:
    if pid in CURATED_IDS:
        # A curated fixture already owns this id (a random patient would
        # otherwise collide with it on insert) — skip the id WITHOUT drawing
        # from the RNG, so every other generated patient's values are exactly
        # what they would be if the curated ids simply weren't in this range.
        pid += 1
        continue
    generated_count += 1
    first = random.choice(FIRST); last = random.choice(LAST)
    name = f"{first} {last}"
    year = random.randint(1940, 2007); month = random.randint(1,12); day = random.randint(1,28)
    dob = f"{year:04d}-{month:02d}-{day:02d}"
    ssn = f"{random.randint(200,699):03d}-{random.randint(10,99):02d}-{random.randint(1000,9999):04d}"
    g = random.choice(GENDERS)
    city, zc = random.choice(CITIES)
    addr = f"{random.randint(10,9999)} {random.choice(STREETS)}, {city}, CA {zc}"
    phone = f"310-555-{random.randint(0,9999):04d}"
    email = f"{first.lower()}.{last.lower()}{random.randint(1,99)}@example.com"
    mrn = f"M{random.randint(1000,9999)}"
    via = random.choice(["self_service","front_desk","front_desk"])
    days_ago = random.randint(5, 1500)
    created = (datetime(2026,6,20) - timedelta(days=days_ago)).strftime("%Y-%m-%d %H:%M:%S")
    notes = random.choice(["", "", "", "Prefers afternoon appts.", "Spanish-speaking.",
                           "Wheelchair access needed.", "No known issues.", "Follow-up requested."])
    prows.append(f" ({pid}, {sql_str(mrn)}, {sql_str(name)}, {sql_str(dob)}, {sql_str(ssn)}, {sql_str(g)}, {sql_str(addr)}, {sql_str(phone)}, {sql_str(email)}, {sql_str(notes)}, {sql_str(via)}, {sql_str(created)})")
    gen_patient_ids.append(pid)
    pid += 1
emit(",\n".join(prows) + ";")
max_pid = pid - 1
emit(f"SELECT setval('patients_id_seq', {max_pid}, true);")
emit()

# The two pre-activated patient portal accounts, now that their patients rows
# exist. Deferred from the main users INSERT above — see that section's
# comment for why (users.patient_id's FK cannot be satisfied any earlier).
emit("INSERT INTO users (id, username, password_hash, full_name, role, patient_id, created_at) VALUES")
purows = []
for patient_id, full_name in PATIENT_USERS:
    uid = patient_user_id_of[patient_id]
    salt = f"riverbendp{patient_id}saltval"  # fixed -> deterministic output
    h = hash_password(PATIENT_DEMO_PASSWORD, salt)
    uname = f"patient-{patient_id}"
    purows.append(
        f" ({uid}, {sql_str(uname)}, {sql_str(h)}, {sql_str(full_name)}, 'patient', {patient_id}, now())"
    )
emit(",\n".join(purows) + ";")
emit()

all_patient_ids = [1042,1043,1330,1588,1601] + gen_patient_ids

# ---------------------------------------------------------------------------
# providers
# ---------------------------------------------------------------------------
PROVIDERS = [
    (1,"Dr. Anil Patel","Family Medicine","Riverbend Main"),
    (2,"Dr. Anita Nguyen","Internal Medicine","Riverbend Main"),
    (3,"Dr. Sandra Lee","Pediatrics","Riverbend North"),
    (4,"Dr. Omar Haddad","Cardiology","Riverbend Main"),
    (5,"Dr. Grace Kim","Dermatology","Riverbend North"),
    (6,"Lab Services","Laboratory","Riverbend Main"),
    (7,"Imaging Center","Radiology","Riverbend Main"),
    (8,"Dr. Beatriz Alvarez","OB/GYN","Riverbend South"),
]
emit("INSERT INTO providers (id, name, specialty, location) VALUES")
emit(",\n".join(f" ({i}, {sql_str(n)}, {sql_str(s)}, {sql_str(l)})" for i,n,s,l in PROVIDERS) + ";")
emit(f"SELECT setval('providers_id_seq', {len(PROVIDERS)}, true);")
emit()

# ---------------------------------------------------------------------------
# slots — explicit ids incl. 88231 (double-booked) and 88240.
#
# w9-fixes P0 4.2 follow-up: status used to be an independent random draw
# right here, decided before a single appointment existed to place against
# it — the exact shape of bug 4.2 is about (Slot.status disagreeing with
# whether a confirmed appointment actually occupies the slot), baked into
# the seed itself rather than caused by anything at runtime. The INSERT is
# now deferred (see below, after the appointments section) and status is
# derived from confirmed_slots_used once that set is final, so a freshly
# seeded database starts with the two models already in agreement.
slot_base_rows = []
slot_id = 88200
base = datetime(2026, 6, 23, 8, 0, 0)
for n in range(120):
    prov = random.randint(1,8)
    loc = PROVIDERS[prov-1][3]
    start = base + timedelta(days=n // 8, hours=(n % 8))
    end = start + timedelta(minutes=30)
    slot_base_rows.append((slot_id, prov, loc, start, end))
    slot_id += 1

# Dedicated demo-booking pool (w9-fixes P0 4.2 follow-up) — 16 reserved ids,
# well clear of both the random pool above (88200-88319) and the
# curated-fixture range used below (90001-90008), that the historical
# appointment loop never draws from. Always 'open' at generation time with
# no appointment of any kind placed on them. This file's own dates are fixed
# at generation time and eventually fall into the past (services now require
# start_at in the future — see scheduling-service's list_slots/book), so
# what actually keeps "Schedule a visit" demonstrable between rehearsals is
# db/seed/demo_reset.sql repositioning these specific ids relative to
# whenever it runs, not this seed file.
DEMO_SLOT_IDS = list(range(95001, 95017))
demo_slot_base_rows = []
demo_base = datetime(2026, 9, 15, 9, 0, 0)
for i, sid in enumerate(DEMO_SLOT_IDS):
    prov = (i % len(PROVIDERS)) + 1
    loc = PROVIDERS[prov - 1][3]
    start = demo_base + timedelta(days=i // 4, hours=2 * (i % 4))
    end = start + timedelta(minutes=30)
    demo_slot_base_rows.append((sid, prov, loc, start, end))

# ---------------------------------------------------------------------------
# insurance_coverages
# ---------------------------------------------------------------------------
PAYERS = [("Blue Cross Blue Shield","PPO"),("Aetna","PPO"),("UnitedHealthcare","HMO"),
          ("Cigna","PPO"),("Kaiser","HMO"),("Medi-Cal","Medicaid"),("Medicare","Medicare"),
          (None,"self_pay")]
emit("INSERT INTO insurance_coverages (patient_id, payer_name, member_id, group_number, plan_type, status, verified_at) VALUES")
irows = []
# fixtures: Maria's three rows all BCBS4471 (same member id across dup charts)
for pid_ in (1042, 1330, 1588):
    irows.append(f" ({pid_}, 'Blue Cross Blue Shield', 'BCBS4471', 'GRP88', 'PPO', 'active', '2026-06-22 09:14:30')")
irows.append(f" (1043, 'Aetna', 'AETNA9920', 'GRP12', 'PPO', 'active', '2026-06-22 09:17:50')")
# Curated fixtures 1737/1738/1739 — explicit and fixed, so a rerun always
# reproduces the same demo, never a random draw. 1737 stays 'active' per its
# own original requirement ("active insurance and eligibility data"). 1738
# and 1739 are deliberately NOT both 'active' (2026-08-23, W9.4): the
# Coverage & Eligibility workspace needs 'stale' and 'unknown' to be real,
# reachable states on a canonical patient, not something only a random
# generated row happens to land on — see coverage-eligibility.md's essential
# test list ("active/inactive, pending, stale, unavailable, and simulated
# mapping"). Both still have a member id on file, so "Request verification"
# is always available from the seed's own starting state.
irows.append(" (1737, 'Kaiser', 'KAISER5591', 'GRP41', 'HMO', 'active', '2026-03-05 08:55:00')")
irows.append(" (1738, 'Aetna', 'AETNA7381', 'GRP22', 'PPO', 'stale', '2026-03-18 09:25:00')")
irows.append(" (1739, 'UnitedHealthcare', 'UHC7392', 'GRP63', 'HMO', 'unknown', NULL)")
for pid_ in all_patient_ids:
    if pid_ in CURATED_IDS or pid_ in (1330, 1588, 1043):
        continue
    payer, plan = random.choice(PAYERS)
    if payer is None:
        irows.append(f" ({pid_}, NULL, NULL, NULL, 'self_pay', 'unknown', NULL)")
    else:
        mid = f"{payer.split()[0][:4].upper()}{random.randint(1000,9999)}"
        status = random.choice(["active","active","active","inactive","unknown"])
        ver = "'2026-06-01 12:00:00'" if status != "unknown" else "NULL"
        irows.append(f" ({pid_}, {sql_str(payer)}, {sql_str(mid)}, 'GRP{random.randint(10,99)}', {sql_str(plan)}, {sql_str(status)}, {ver})")
emit(",\n".join(irows) + ";")
emit()

# ---------------------------------------------------------------------------
# encounters — fixtures (ids 1-5), then curated (1042/1737/1738/1739), then
# generated for everyone else
# ---------------------------------------------------------------------------
emit("INSERT INTO encounters (id, patient_id, encounter_type, provider, reason, location, status, summary, allergies, medications, occurred_at) VALUES")
erows = [
    " (1, 1042, 'office_visit', 'Dr. Patel',  'Annual physical', 'Riverbend Main', 'finished', 'Annual physical. Unremarkable.', '', 'lisinopril', '2026-01-12 09:00:00')",
    " (2, 1330, 'office_visit', 'Dr. Nguyen', 'Sinus infection', 'Riverbend Main', 'finished', 'Sinus infection. Prescribed antibiotic.', 'penicillin', 'amoxicillin', '2026-03-04 11:30:00')",
    " (3, 1588, 'lab',          'Lab',        'CBC panel', 'Riverbend Main', 'finished', 'CBC panel within normal limits.', '', '', '2026-05-19 08:15:00')",
    " (4, 1043, 'office_visit', 'Dr. Patel',  'Hearing aid follow-up', 'Riverbend Main', 'finished', 'Hearing aid follow-up.', '', '', '2026-02-20 14:00:00')",
    " (5, 1601, 'office_visit', 'Dr. Nguyen', 'New patient intake', 'Riverbend Main', 'finished', 'New patient intake.', 'none known', '', '2026-06-23 10:30:00')",
]
ETYPES = ["office_visit","office_visit","lab","imaging","telehealth"]
REASONS = ["Annual physical","Follow-up","Acute visit","Lab draw","Imaging","Med refill","Consult"]
ALLERGY_POOL = ["", "", "", "penicillin", "sulfa", "latex", "peanuts", "none known"]
MED_POOL = ["", "", "lisinopril", "metformin", "atorvastatin", "albuterol", "levothyroxine", "amoxicillin"]

# curated_encounter_ids tracks every encounter id the RANDOM records loop
# below must never touch — the original 5 hand-authored fixtures (whose
# records are also hand-authored, one each) plus every encounter the curated
# blocks below create. Named as a set rather than reusing the old "e <= 5"
# threshold: that threshold only worked because the 5 original fixtures
# happened to be the lowest ids in the file, which stops being true the
# moment new curated encounters exist above id 5.
curated_encounter_ids = {1, 2, 3, 4, 5}

enc_id = 6
enc_by_patient = {}

# --- curated encounters: 1042 (hyperlipidemia), 1737 (diabetes), 1738
# (hypertension), 1739 (asthma). Three real visits each, none random, so a
# demo run reads the same chart every rehearsal. Encounter dates walk forward
# to match the two dated lab results each patient's records block adds below.
CURATED_ENCOUNTERS = {
    1042: [
        ("office_visit", "Dr. Patel", "Hyperlipidemia follow-up", "Riverbend Main",
         "Lipid panel reviewed. Started atorvastatin 20mg nightly.", "", "atorvastatin",
         "2026-03-02 09:00:00"),
        ("lab", "Lab Services", "Lipid panel draw", "Riverbend Main",
         "Fasting lipid panel drawn for statin follow-up.", "", "atorvastatin",
         "2026-05-14 08:30:00"),
        ("office_visit", "Dr. Patel", "Hyperlipidemia follow-up", "Riverbend Main",
         "LDL improved on atorvastatin. Continue current dose, recheck in 6 months.", "",
         "atorvastatin", "2026-08-06 09:15:00"),
    ],
    1737: [
        ("office_visit", "Dr. Nguyen", "Type 2 diabetes follow-up", "Riverbend Main",
         "Diabetes follow-up. Discussed nutrition and exercise.", "", "metformin",
         "2026-03-12 09:00:00"),
        ("lab", "Lab Services", "A1c draw", "Riverbend Main",
         "A1c drawn for diabetes management.", "", "metformin", "2026-06-02 08:20:00"),
        ("office_visit", "Dr. Nguyen", "Type 2 diabetes follow-up", "Riverbend Main",
         "A1c improved with dietary changes and metformin. Continue current plan, "
         "recheck in 6 months.", "", "metformin", "2026-08-11 09:45:00"),
    ],
    1738: [
        ("office_visit", "Dr. Patel", "Hypertension follow-up", "Riverbend Main",
         "Hypertension follow-up. Started lisinopril 10mg daily.", "", "lisinopril",
         "2026-03-18 09:30:00"),
        ("lab", "Lab Services", "Basic metabolic panel draw", "Riverbend Main",
         "Basic metabolic panel drawn for ACE-inhibitor follow-up.", "", "lisinopril",
         "2026-06-09 08:10:00"),
        ("office_visit", "Dr. Patel", "Hypertension follow-up", "Riverbend Main",
         "Blood pressure improved on lisinopril. Continue current dose, recheck in "
         "6 months.", "", "lisinopril", "2026-08-14 09:20:00"),
    ],
    1739: [
        ("office_visit", "Dr. Nguyen", "Asthma follow-up", "Riverbend Main",
         "Asthma follow-up. Reviewed inhaler technique.", "", "albuterol, fluticasone",
         "2026-03-22 14:30:00"),
        ("lab", "Lab Services", "Peak flow and pulse oximetry", "Riverbend Main",
         "Peak flow and oxygen saturation measured for asthma follow-up.", "",
         "albuterol, fluticasone", "2026-06-11 08:45:00"),
        ("office_visit", "Dr. Nguyen", "Asthma follow-up", "Riverbend Main",
         "Oxygen saturation improved with controller adherence. Continue current "
         "plan, recheck in 6 months.", "", "albuterol, fluticasone", "2026-08-13 09:40:00"),
    ],
}
curated_encounter_id_of = {}   # (patient_id, index) -> encounter id, for the records block below
for pid_, visits in CURATED_ENCOUNTERS.items():
    for idx, (etype, prov, reason, loc, summ, allergies, meds, occ) in enumerate(visits):
        erows.append(
            f" ({enc_id}, {pid_}, {sql_str(etype)}, {sql_str(prov)}, {sql_str(reason)}, "
            f"{sql_str(loc)}, 'finished', {sql_str(summ)}, {sql_str(allergies)}, "
            f"{sql_str(meds)}, {sql_str(occ)})"
        )
        enc_by_patient.setdefault(pid_, []).append(enc_id)
        curated_encounter_ids.add(enc_id)
        curated_encounter_id_of[(pid_, idx)] = enc_id
        enc_id += 1

for pid_ in all_patient_ids:
    if pid_ in CURATED_IDS:
        continue
    n_enc = random.choices([0,1,2,3,4],[1,4,4,2,1])[0]
    for _ in range(n_enc):
        prov = random.choice(PROVIDERS)
        etype = random.choice(ETYPES)
        reason = random.choice(REASONS)
        days_ago = random.randint(1, 1200)
        occ = (datetime(2026,6,20) - timedelta(days=days_ago)).strftime("%Y-%m-%d %H:%M:%S")
        summ = f"{reason}. {random.choice(['Stable.','Improving.','No acute distress.','Counseled patient.','Routine.'])}"
        allergies = random.choice(ALLERGY_POOL)
        meds = random.choice(MED_POOL)
        erows.append(f" ({enc_id}, {pid_}, {sql_str(etype)}, {sql_str(prov[1])}, {sql_str(reason)}, {sql_str(prov[3])}, 'finished', {sql_str(summ)}, {sql_str(allergies)}, {sql_str(meds)}, {sql_str(occ)})")
        enc_by_patient.setdefault(pid_, []).append(enc_id)
        enc_id += 1
# ensure fixtures map
for k,v in {1042:[1],1330:[2],1588:[3],1043:[4],1601:[5]}.items():
    enc_by_patient.setdefault(k, []).extend(v)
emit(",\n".join(erows) + ";")
emit(f"SELECT setval('encounters_id_seq', {enc_id-1}, true);")
emit()

# ---------------------------------------------------------------------------
# records — fixtures (ids 1-5), then curated, then generated (no index on
# body = full scan)
# ---------------------------------------------------------------------------
emit("INSERT INTO records (id, encounter_id, patient_id, kind, title, body, status, reference_range, created_at) VALUES")
rrows = [
    " (1, 1, 1042, 'note', 'Visit note', 'Patient in good health.', 'final', NULL, '2026-01-12 09:20:00')",
    " (2, 2, 1330, 'note', 'Visit note', 'Penicillin allergy confirmed. Switched to non-PCN class.', 'final', NULL, '2026-03-04 11:45:00')",
    " (3, 3, 1588, 'lab_result', 'CBC panel', 'WBC 6.1, RBC 4.7, Hgb 14.2.', 'normal', 'WBC 4.0-11.0; Hgb 13.5-17.5', '2026-05-19 09:00:00')",
    " (4, 4, 1043, 'note', 'Visit note', 'Hearing stable.', 'final', NULL, '2026-02-20 14:20:00')",
    " (5, 5, 1601, 'note', 'Visit note', 'Established care.', 'final', NULL, '2026-06-23 10:50:00')",
]
LAB_TESTS = [("CBC panel","WBC 6.1, RBC 4.7, Hgb 14.2.","WBC 4.0-11.0; Hgb 13.5-17.5"),
             ("Lipid panel","Total chol 188, LDL 102, HDL 55.","LDL <130; HDL >40"),
             ("A1c","6.2%.","<5.7% normal; 5.7-6.4% prediabetes"),
             ("Basic metabolic","Na 140, K 4.1, Cr 0.9.","Na 135-145; K 3.5-5.1"),
             ("TSH","2.3 mIU/L.","0.4-4.0 mIU/L")]
rec_id = 6

# --- curated records: two dated trend results + one narrative/unquotable
# note per curated patient. Deliberately NOT random (see the A1c comment this
# generalises, kept below): the demo has to read the same way every
# rehearsal, and each trend pair is what proves the arithmetic path against a
# real prior date rather than "unchanged 0.0" against now().
#
# quote+compute:  a single scalar value, a unit patient_summary.py's
#                 _UNITS_SAFE_FOR_ARITHMETIC allows, at two dates.
# narrative:      kind='note' — never in _QUOTABLE_KINDS, so it is UNQUOTABLE
#                 by construction and exercises the refusal + clinician-review
#                 path (review_queue.enqueue_refusals queues it on first read;
#                 nothing here pre-approves it — the review starts clean).
CURATED_TRENDS = {
    # patient_id: (title, unit-bearing label, reference_range, [(index, value, date)])
    1042: ("LDL", "LDL", "mg/dL", "LDL <130 mg/dL",
           [(0, "162", "2026-03-02 09:20:00"), (2, "118", "2026-08-06 09:35:00")]),
    1737: ("A1c", "", "%", "<5.7% normal; 5.7-6.4% prediabetes",
           [(0, "7.5", "2026-03-12 09:15:00"), (2, "6.2", "2026-08-11 10:05:00")]),
    1738: ("Systolic BP", "Systolic BP", "mmHg", "Normal <120 mmHg; Stage 2 >=140 mmHg",
           [(0, "158", "2026-03-18 09:50:00"), (2, "132", "2026-08-14 09:40:00")]),
    1739: ("SpO2", "SpO2", "%", "Normal 95-100%",
           [(0, "90", "2026-03-22 14:50:00"), (2, "96", "2026-08-13 10:00:00")]),
}
CURATED_NARRATIVES = {
    1042: "Discussed statin side effects and adherence. No muscle pain reported.",
    1737: "Discussed insulin as a future option if A1c does not continue to improve. "
          "Patient prefers to continue with diet and metformin for now.",
    1738: "Discussed home blood pressure monitoring and low-sodium diet. Patient "
          "using a home cuff twice weekly.",
    1739: "Reviewed asthma action plan and rescue inhaler technique. Discussed "
          "trigger avoidance at home.",
}
for pid_, (title, label, unit, ref_range, points) in CURATED_TRENDS.items():
    for idx, value, created in points:
        enc_id_for = curated_encounter_id_of[(pid_, idx)]
        sep = "" if unit == "%" else " "
        body = f"{label} {value}{sep}{unit}." if label else f"{value}{sep}{unit}."
        rrows.append(
            f" ({rec_id}, {enc_id_for}, {pid_}, 'lab_result', {sql_str(title)}, "
            f"{sql_str(body)}, 'final', {sql_str(ref_range)}, {sql_str(created)})"
        )
        rec_id += 1
    # The narrative sits on the middle (lab-draw) encounter — a real visit
    # note alongside the two dated results, not a fourth encounter.
    narrative_enc_id = curated_encounter_id_of[(pid_, 1)]
    narrative_date = CURATED_ENCOUNTERS[pid_][1][-1]
    rrows.append(
        f" ({rec_id}, {narrative_enc_id}, {pid_}, 'note', 'Visit note', "
        f"{sql_str(CURATED_NARRATIVES[pid_])}, 'final', NULL, {sql_str(narrative_date)})"
    )
    rec_id += 1

# Peak flow (L/min is not in patient_summary's arithmetic allowlist, so this
# quotes cleanly but never computes a change — asthma's SpO2 trend above is
# the computable one; this is the additional quotable-only result the fixture
# calls for).
peak_flow_enc = curated_encounter_id_of[(1739, 1)]
rrows.append(
    f" ({rec_id}, {peak_flow_enc}, 1739, 'lab_result', 'Peak flow', "
    f"'Peak flow 380 L/min.', 'final', 'Personal best 420 L/min', '2026-06-11 08:50:00')"
)
rec_id += 1

# A multi-value PANEL on 1737, specifically. tests/integration/
# test_patient_summary_flow.py::test_a_panel_result_still_shows_its_values and
# test_patient_acceptance_e2e.py::test_negative_a_multi_value_panel_produces_no_inferred_delta
# both require patient 1737's chart to contain a panel-shaped result — quoted,
# but never carrying a computed change. Multiple comma-joined values is what
# makes classify() call this a panel rather than a single_value.
panel_enc = curated_encounter_id_of[(1737, 1)]
rrows.append(
    f" ({rec_id}, {panel_enc}, 1737, 'lab_result', 'Basic metabolic', "
    f"'Na 140, K 4.1, Cr 0.9.', 'final', 'Na 135-145; K 3.5-5.1', '2026-06-02 08:25:00')"
)
rec_id += 1

# A second unquotable note on 1737, specifically. 1737 is THE demo patient
# (docs/runbook.md, tests/integration/test_demo_reset.py) and the rehearsal
# regression test walks the review queue to at least 2 cases (approve one,
# reject the other) to prove make demo-reset restores a genuinely consumed
# state, not a still-untouched one. One narrative record is the floor every
# curated patient meets; 1737 needs a second to be rehearsed against at all.
third_enc = curated_encounter_id_of[(1737, 2)]
rrows.append(
    f" ({rec_id}, {third_enc}, 1737, 'note', 'Visit note', "
    f"'Reviewed continuous glucose monitor data with patient. Discussed patterns "
    f"around evening meals.', 'final', NULL, '2026-08-11 09:50:00')"
)
rec_id += 1

for pid_, encs in enc_by_patient.items():
    if pid_ in CURATED_IDS:
        continue
    for e in encs:
        if e in curated_encounter_ids:
            continue
        for _ in range(random.choices([1,1,2,3],[3,3,2,1])[0]):
            kind = random.choice(["note","note","lab_result","imaging","immunization"])
            if kind == "lab_result":
                t,b,rr = random.choice(LAB_TESTS)
                status = random.choice(["normal","normal","abnormal","preliminary"])
                rrows.append(f" ({rec_id}, {e}, {pid_}, 'lab_result', {sql_str(t)}, {sql_str(b)}, {sql_str(status)}, {sql_str(rr)}, now())")
            elif kind == "imaging":
                rrows.append(f" ({rec_id}, {e}, {pid_}, 'imaging', 'Imaging report', {sql_str(random.choice(['Chest X-ray: no acute findings.','Knee MRI: mild effusion.','Abdominal US: unremarkable.']))}, 'final', NULL, now())")
            elif kind == "immunization":
                rrows.append(f" ({rec_id}, {e}, {pid_}, 'immunization', 'Immunization', {sql_str(random.choice(['Influenza vaccine administered.','Tdap administered.','COVID-19 booster administered.']))}, 'final', NULL, now())")
            else:
                rrows.append(f" ({rec_id}, {e}, {pid_}, 'note', 'Visit note', {sql_str(random.choice(['Patient stable.','Continue current plan.','Labs reviewed.','Counseled on diet/exercise.','RTC in 6 months.']))}, 'final', NULL, now())")
            rec_id += 1

emit(",\n".join(rrows) + ";")
emit(f"SELECT setval('records_id_seq', {rec_id-1}, true);")
emit()


# ---------------------------------------------------------------------------
# appointments — fixtures (RIV-175 double-booking, reconciled) then generated
# ---------------------------------------------------------------------------
# Stage 4 (Week 5, RIV-175, migration 013) added a partial UNIQUE index (at
# most one 'confirmed' appointment per slot_id) plus idempotency_key /
# reconciled_duplicate_of columns. A fresh volume loads db/schema.sql (which
# now includes that index) BEFORE this file, so seed data itself must never
# have two 'confirmed' rows for the same slot_id or the INSERT below fails
# outright. Two things follow from that:
#   1. The hand-authored slot-88231 fixture now reflects the
#      POST-reconciliation state migration 013 actually produces on real
#      dirty data (see the migration's own comment) — one confirmed row,
#      one reclassified to cancelled_duplicate pointing back at it — rather
#      than the two-confirmed-rows race it used to depict. It still exists
#      specifically to demonstrate that race happened; it just can no
#      longer be *stored* mid-race. idempotency_key is NULL on both: this
#      fixture predates idempotency keys entirely, which is exactly why the
#      race wasn't caught before now.
#   2. The generator must not hand out a slot_id already used by a
#      'confirmed' row to a second 'confirmed' row — confirmed_slots_used
#      tracks every slot already spent this way (seeded with the fixture's
#      own slots) and only picks from what's left.
emit("INSERT INTO appointments (patient_id, slot_id, provider, reason, location, scheduled_for, status, created_at, idempotency_key, reconciled_duplicate_of) VALUES")
arows = [
    " (1042, 88231, 'Dr. Patel', 'Follow-up', 'Riverbend Main', '2026-06-26 08:00:00', 'confirmed', '2026-06-22 09:31:04.120', NULL, NULL)",
    " (1588, 88231, 'Dr. Patel', 'Follow-up', 'Riverbend Main', '2026-06-26 08:00:00', 'cancelled_duplicate', '2026-06-22 09:31:04.519', NULL, 1)",
    " (1043, 88240, 'Dr. Nguyen', 'Hearing follow-up', 'Riverbend Main', '2026-06-27 09:00:00', 'confirmed', '2026-06-22 10:05:00.000', NULL, NULL)",
]
confirmed_slots_used = {88231, 88240}

# Curated fixtures: one COMPLETED (past) and one upcoming CONFIRMED
# appointment each, on fresh slot ids (90000+) well clear of both the random
# pool above (88200-88319) and the RIV-175 double-booking fixture — so a
# rerun can never collide with either, and every curated patient's scheduling
# workflow has deterministic evidence.
curated_slot_id = 90001
for pid_ in (1042, 1737, 1738, 1739):
    prov = PROVIDERS[0] if pid_ == 1042 else PROVIDERS[1]
    arows.append(
        f" ({pid_}, {curated_slot_id}, {sql_str(prov[1])}, 'Follow-up', {sql_str(prov[3])}, "
        f"'2026-08-06 09:00:00', 'completed', '2026-08-01 09:00:00.000', NULL, NULL)"
    )
    curated_slot_id += 1
    arows.append(
        f" ({pid_}, {curated_slot_id}, {sql_str(prov[1])}, 'Follow-up', {sql_str(prov[3])}, "
        f"'2026-09-10 09:00:00', 'confirmed', '2026-08-15 09:00:00.000', NULL, NULL)"
    )
    curated_slot_id += 1

for pid_ in all_patient_ids:
    if pid_ in CURATED_IDS:
        continue
    for _ in range(random.choices([0,1,2],[2,3,1])[0]):
        prov = random.choice(PROVIDERS)
        reason = random.choice(REASONS)
        days_fwd = random.randint(1, 30)
        sched = (datetime(2026,6,24) + timedelta(days=days_fwd, hours=random.randint(0,8))).strftime("%Y-%m-%d %H:%M:%S")
        created = (datetime(2026,6,1) + timedelta(days=random.randint(0,20))).strftime("%Y-%m-%d %H:%M:%S")
        status = random.choice(["confirmed","confirmed","confirmed","cancelled","completed"])
        if status == "confirmed":
            available = [s for s in range(88200, slot_id) if s not in confirmed_slots_used]
            if available:
                s_id = random.choice(available)
                confirmed_slots_used.add(s_id)
            else:
                # Demand for "confirmed" this loop can exceed the 120-slot
                # pool (many more patients than slots) — once every slot
                # already has a confirmed appointment, this visit couldn't
                # actually have been confirmed either; reflect that as
                # 'completed' (it happened) rather than silently colliding
                # with an already-confirmed slot.
                status = "completed"
                s_id = random.randint(88200, slot_id - 1)
        else:
            s_id = random.randint(88200, slot_id-1)
        arows.append(f" ({pid_}, {s_id}, {sql_str(prov[1])}, {sql_str(reason)}, {sql_str(prov[3])}, {sql_str(sched)}, {sql_str(status)}, {sql_str(created)}, NULL, NULL)")
emit(",\n".join(arows) + ";")
emit()

assert not (set(DEMO_SLOT_IDS) & confirmed_slots_used), (
    "the dedicated demo-booking pool must never be drawn into the historical "
    "appointment loop above"
)

# Now that confirmed_slots_used is final, emit slots with status derived
# from it — see the comment where slot_base_rows was built above.
emit("INSERT INTO slots (id, provider_id, location, start_at, end_at, status) VALUES")
all_slot_rows = []
for sid, prov, loc, start, end in slot_base_rows:
    status = "booked" if sid in confirmed_slots_used else "open"
    all_slot_rows.append(
        f" ({sid}, {prov}, {sql_str(loc)}, {sql_str(start.strftime('%Y-%m-%d %H:%M:%S'))}, "
        f"{sql_str(end.strftime('%Y-%m-%d %H:%M:%S'))}, {sql_str(status)})"
    )
for sid, prov, loc, start, end in demo_slot_base_rows:
    all_slot_rows.append(
        f" ({sid}, {prov}, {sql_str(loc)}, {sql_str(start.strftime('%Y-%m-%d %H:%M:%S'))}, "
        f"{sql_str(end.strftime('%Y-%m-%d %H:%M:%S'))}, 'open')"
    )
emit(",\n".join(all_slot_rows) + ";")
emit(f"SELECT setval('slots_id_seq', {max(DEMO_SLOT_IDS)}, true);")
emit()

# ---------------------------------------------------------------------------
# consents
# ---------------------------------------------------------------------------
emit("INSERT INTO consents (patient_id, kind, signed_at) VALUES")
crows = [
    " (1042, 'npp_ack', now())", " (1042, 'treatment_consent', now())",
    " (1043, 'npp_ack', now())", " (1601, 'npp_ack', now())",
    " (1737, 'npp_ack', now())", " (1737, 'treatment_consent', now())",
    " (1738, 'npp_ack', now())", " (1738, 'treatment_consent', now())",
    " (1739, 'npp_ack', now())", " (1739, 'treatment_consent', now())",
]
for pid_ in gen_patient_ids:
    if random.random() < 0.85:
        crows.append(f" ({pid_}, 'npp_ack', now())")
    if random.random() < 0.7:
        crows.append(f" ({pid_}, 'treatment_consent', now())")
emit(",\n".join(crows) + ";")
emit()

# ---------------------------------------------------------------------------
# patient_access_grants — Week 4 catch-up (migration 014): the real
# per-(actor, patient) authorization fact SqlPatientAccessGate checks
# (services/records-service/patient_access_gate.py), replacing the
# authenticated-staff-only StaffAccessGate. Deliberately different scopes
# per user, not a blanket "everyone sees everything" grant:
#   frontdesk registers/handles the Maria Gonzalez charts (1042/1330/1588,
#     all the SAME person under three unmerged rows — see the module
#     docstring above) and Aisha Khan (1601, front_desk-registered).
#   rdelgado is the registration user used in the duplicate-records demo, so
#     she is assigned the same Maria Gonzalez cluster. Reconciliation checks
#     every source chart independently; granting only 1042 would correctly
#     hide 1330/1588 and make the demo look like no duplicate was found.
#   drpatel is James O'Brien's (1043) physician (encounter 4's provider).
#   drnguyen also treats Maria Gonzalez's 1330 chart and Aisha Khan (1601)
#     — encounters 2 and 5's provider — overlapping with frontdesk's grants
#     on purpose (multiple staff legitimately need the same chart).
#   drkim is the S3 review-queue clinician. Granted 1737 ONLY, deliberately:
#     the queue is grant-scoped like every other chart read, so a blanket
#     grant would hide exactly the bug the scoping exists to prevent — a
#     reviewer seeing withheld notes for patients they never treated. 1629
#     is left ungranted so the "an ungranted clinician sees nothing" test has
#     a real account to prove it with.
# frontdesk is deliberately NOT granted 1043 — tests/integration/
# test_records_flow.py::test_user_cannot_read_other_patients_chart and
# test_patient_view_flow.py rely on exactly this to prove cross-patient
# denial with real seeded accounts, not just unit-test fixtures.
# ---------------------------------------------------------------------------
# PR #23 review round 2 (2026-08-07): grants are keyed on users.id (the stable
# principal the gateway forwards as X-Actor-Id), never username. Ids from the
# users INSERT above: frontdesk=2, rdelgado=3, drpatel=5, drnguyen=6, drkim=13.
emit("INSERT INTO patient_access_grants (user_id, patient_id) VALUES")
gwrows = [
    " (2, 1042)", " (2, 1330)", " (2, 1588)", " (2, 1601)",   # frontdesk
    " (3, 1042)", " (3, 1330)", " (3, 1588)",                  # rdelgado
    " (5, 1043)",                                             # drpatel
    " (6, 1330)", " (6, 1601)",                               # drnguyen (treating provider, unrelated to the clinician matrix below)
    # frontdesk (2026-08-22): tests/integration/test_patient_acceptance_e2e.py
    # and test_patient_summary_flow.py both drive the invitation for 1737
    # through the `frontdesk` account, and invitation issuance now requires an
    # active grant for the specific chart (services/gateway/app.py's
    # has_active_grant check), not merely the patients.write permission.
    " (2, 1737)",                                             # frontdesk
    # frontdesk / 1629 (2026-08-22): same reasoning as 1737 above —
    # tests/integration/test_patient_acceptance_e2e.py activates patient B
    # (1629, "the other patient, used only to prove they cannot be reached")
    # through frontdesk too, and now needs a grant to do it.
    " (2, 1629)",                                             # frontdesk
    # Curated fixtures (2026-08-22). drpatel is the treating provider named on
    # 1738's own curated encounters (hypertension) — a chart-access grant,
    # not a review-queue one: `staff` (drpatel's role) does not hold
    # summary_review.decide, so this never lets drpatel see or decide a case.
    # frontdesk registers all four canonical patients.
    " (5, 1738)",                                             # drpatel (treating provider)
    " (2, 1738)", " (2, 1739)",                                # frontdesk
    #
    # --- the clinician reviewer matrix (2026-08-22) -------------------------
    # Two clinician accounts, deliberately overlapping on ONE patient so the
    # shared-queue case is demonstrable — a single reviewer can only ever
    # prove exclusive access, never that two independent grants on the same
    # chart coexist without either one seeing more than the other allows.
    #
    #   drkim    : 1042, 1737, 1738   (NOT 1739)
    #   drnguyen : 1738, 1739         (NOT 1042, NOT 1737)
    #
    # 1738 (Thomas Johnson) is the deliberate overlap: both clinicians hold an
    # active grant for it, so a review-queue listing shows it to both, and a
    # decision either one makes must not be silently overwritable by the
    # other (services/records-service/review_queue.py's existing
    # only-a-VALIDATED-draft/pending-case transition guard already enforces
    # this generically — it has no special case for "more than one reviewer
    # holds a grant" because the grant only decides WHO can attempt a
    # transition, never how many attempts a case tolerates).
    " (13, 1042)", " (13, 1737)", " (13, 1738)",               # drkim
    " (6, 1738)", " (6, 1739)",                                # drnguyen
]
# Self-grants for the two pre-activated patient accounts — the same fact and
# the same table a real activation writes (services/gateway/app.py's
# _activate_invitation), not a second authorization path. 1042 and 1737 have
# no such row: neither has a seeded account.
for patient_id, uid in patient_user_id_of.items():
    gwrows.append(f" ({uid}, {patient_id})")
emit(",\n".join(gwrows) + ";")
emit()

# ---------------------------------------------------------------------------
# roi_requests — note: NO authorization linkage captured (164.508 not enforced)
# ---------------------------------------------------------------------------
emit("INSERT INTO roi_requests (patient_id, requested_by, recipient, recipient_type, purpose, date_range_start, date_range_end, status, created_at) VALUES")
RECIP = [("Dr. Smith Cardiology","provider"),("Acme Law LLP","attorney"),
         ("BlueCross Claims","payer"),("Patient (self)","self"),("County Health","provider")]
PURP = ["Continuity of care","Legal matter","Insurance claim","Personal copy","Referral"]
rqrows = []
for _ in range(16):
    pid_ = random.choice(all_patient_ids)
    recip, rtype = random.choice(RECIP)
    purpose = random.choice(PURP)
    status = random.choice(["pending","pending","fulfilled","denied"])
    created = (datetime(2026,5,1) + timedelta(days=random.randint(0,55))).strftime("%Y-%m-%d %H:%M:%S")
    rqrows.append(f" ({pid_}, {sql_str(random.choice(['roiclerk','frontdesk','billing1']))}, {sql_str(recip)}, {sql_str(rtype)}, {sql_str(purpose)}, '2024-01-01', '2026-06-01', {sql_str(status)}, {sql_str(created)})")
emit(",\n".join(rqrows) + ";")
emit()

# ---------------------------------------------------------------------------
# disclosures — historical releases, missing authorization/purpose linkage
# ---------------------------------------------------------------------------
emit("INSERT INTO disclosures (patient_id, roi_request_id, disclosed_to, disclosed_at) VALUES")
drows = []
for i in range(8):
    pid_ = random.choice(all_patient_ids)
    drows.append(f" ({pid_}, NULL, {sql_str(random.choice([r[0] for r in RECIP]))}, {sql_str((datetime(2026,5,5)+timedelta(days=i*4)).strftime('%Y-%m-%d %H:%M:%S'))})")
emit(",\n".join(drows) + ";")
emit()

# ---------------------------------------------------------------------------
# audit_logs — "audit" rows are really app INFO logs with PHI in them
# ---------------------------------------------------------------------------
emit("INSERT INTO audit_logs (actor, message) VALUES")
alrows = [
    " ('intake-service', 'POST /intake body={\"name\":\"Maria Gonzalez\",\"dob\":\"1971-03-02\",\"ssn\":\"412-55-9981\"}')",
    " ('records-service', 'GET /patients/1042/records 200')",
]
for _ in range(20):
    pid_ = random.choice(all_patient_ids)
    alrows.append(f" ('records-service', {sql_str(f'GET /patients/{pid_}/records 200')})")
emit(",\n".join(alrows) + ";")
emit()

# ---------------------------------------------------------------------------
# message_threads / thread_messages / thread_read_state — W9.2 demo fixtures
# (2026-08-23, W9.4)
#
# Only 1738 and 1739 get a seeded thread: they are the two curated patients
# with a real portal account already (1042/1737 are invite-ready — there is
# no patient-role user yet to be the sender of a message from them). Two
# threads are enough to demonstrate both essential, distinct states without
# a third patient: 1738's is unread by BOTH of its granted clinicians (the
# same drkim+drnguyen overlap the grant matrix demonstrates elsewhere, so
# the shared-inbox behavior and the unread state are shown together), 1739's
# is a full patient-asks/clinician-replies exchange the patient has already
# read.
# ---------------------------------------------------------------------------
thomas_user_id = patient_user_id_of[1738]
aisha_user_id = patient_user_id_of[1739]
DRKIM_ID, DRNGUYEN_ID = 13, 6  # USERS list order above — see the grant matrix comment on gwrows

emit("INSERT INTO message_threads (id, patient_id, subject, status, created_by, created_at, updated_at) VALUES")
emit(f" (1, 1738, 'Question about my blood pressure readings', 'open', {thomas_user_id}, '2026-08-20 09:00:00', '2026-08-20 09:00:00'),")
emit(f" (2, 1739, 'Refill request for my inhaler', 'open', {aisha_user_id}, '2026-08-18 14:00:00', '2026-08-18 14:32:00');")
emit()

emit("INSERT INTO thread_messages (id, thread_id, sender_user_id, body, idempotency_key, created_at) VALUES")
emit(f" (1, 1, {thomas_user_id}, 'My home readings have been running a bit high this week, should I be concerned?', 'seed-1738-msg-1', '2026-08-20 09:00:00'),")
emit(f" (2, 2, {aisha_user_id}, 'Hi, I am almost out of my albuterol inhaler, can you send a refill?', 'seed-1739-msg-1', '2026-08-18 14:00:00'),")
emit(f" (3, 2, {DRNGUYEN_ID}, 'Sent a refill to your pharmacy on file. Let us know if you do not see it by tomorrow.', 'seed-1739-msg-2', '2026-08-18 14:32:00');")
emit()
emit("SELECT setval('message_threads_id_seq', 2, true);")
emit("SELECT setval('thread_messages_id_seq', 3, true);")
emit()

# 1739's thread has been read by the patient (their own view of drnguyen's
# reply) but deliberately NOT by drnguyen — a real, reachable unread row
# rather than a demo that starts pre-cleared. 1738's thread has no read
# state at all: unread for every one of its granted clinicians, which is
# exactly what the "unread" essential test needs to be true from a fresh
# seed, not only after some other action runs first.
emit("INSERT INTO thread_read_state (thread_id, user_id, last_read_message_id, updated_at) VALUES")
emit(f" (2, {aisha_user_id}, 3, '2026-08-18 15:00:00');")
emit()

print("\n".join(OUT))
